export const ADD_BUDGET = 'ADD_BUDGET'
export const REMOVE_BUDGET = 'REMOVE_BUDGET'

export const ADD_RECURRING_EVENT = 'ADD_RECURRING_EVENT'
export const REMOVE_RECURRING_EVENT = 'REMOVE_RECURRING_EVENT'
export const UPDATE_RECURRING_EVENT = 'UPDATE_RECURRING_EVENT'

export const ADD_CASH_ACCOUNT = 'ADD_CASH_ACCOUNT'
export const REMOVE_CASH_ACCOUNT = 'REMOVE_CASH_ACCOUNT'
export const UPDATE_CASH_ACCOUNT = 'UPDATE_CASH_ACCOUNT'

export const UPDATE_FORECAST = 'SET_FORECAST'

export const SET_IS_CONNECTED = 'SET_IS_CONNECTED'
